# GET request to fetch data
GET {{baseUrl}}/{{version}}/spots
Content-Type: application/json

###

# GET request to fetch a single spot based on its id
GET {{baseUrl}}/{{version}}/spots/6729f53f886e570c85aeee62
Content-Type: application/json


###

# GET request to fetch only certain fields of single spot based on its id
GET {{baseUrl}}/{{version}}/spots/6729f53f886e570c85aeee62?fields[]=title&fields[]=description
Content-Type: application/json

###

# GET request to fetch only certain fields of single spot based on its id but the field is missing
GET {{baseUrl}}/{{version}}/spots/6729f4c5954595eac019435d?fields[]=socialMediaHandles
Content-Type: application/json


###

# GET request to fetch a single spot that doesnt exist
GET {{baseUrl}}/{{version}}/spots/6729f4c5954595eac019435e?fields[]=socialMediaHandles
Content-Type: application/json

###

###

# GET request to fetch a single spot with a id that is invalid
GET {{baseUrl}}/{{version}}/spots/6729f4c5954595eac019435e?fields[]=socialMediaHandles
Content-Type: application/json

###


# POST request to create new data with all fields
POST {{baseUrl}}/{{version}}/spots
Content-Type: application/json

{
    "title": "New Item",
    "address": "New Address",
    "abstract": "New Abstract",
    "description": "New Description",
    "latitude": 1,
    "longitude": 1,
    "email": "test1234@test.com",
    "socialMediaHandles": {
        "twitter": "https://twitter.com",
        "facebook": "https://facebook.com"
    },
    "featuredImageUrl": "https://www.google.com"
}

###

# POST request to create new data with only required fields
POST {{baseUrl}}/{{version}}/spots
Content-Type: application/json

{
    "title": "New Item 2",
    "address": "New Address",
    "description": "New Description",
    "latitude": 1,
    "longitude": 1
}

###

# POST request to create new data (it should fail since there are no required fields)
POST {{baseUrl}}/{{version}}/spots
Content-Type: application/json

{
    "title": "New Item 3"
}
