
openapi: 3.0.0
info:
  title: FairMeet OpenAPI
  description: Questo API server per gestire le richieste di eventi per l'applicazione FairMeet.
  version: '1.0'

servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /event:
    get:
      summary: Prendi tutti eventi con filtri
      responses:
        "200":
          description: Eventi trovati.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
    post:
      summary: Crea nuovo evento
      responses:
        "201":
          description: Nuovo evento creato con successo
          
    delete: 
      summary: Elimina evento esistente
      responses:
        "204":
          description: Evento eliminato con successo

  /user{User_id}:
    get:
      summary: Cerca utente tramite User_id
      responses:
        "200":
          description: utente trovato con successo

    delete:
      summary: Elimina utente tramite User_id
      responses:
        "204":
          description: utente eliminato con successo


  /meeting:   
    get:
      summary: Invia notifica dei gruppi
      responses:
        "200": 
          description: notifica inviata con successo
    post:
      summary: Creazione nuovo gruppo
      responses:
        "201":
          description: gruppo creato con successo
    delete: 
      summary: Elimina gruppo
      responses:
        "204":
          description: gruppo eliminato con successo

  
    
components:
  schemas:
    Event: 
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string 

